targets: ["CHEMBL226", "CHEMBL240", "CHEMBL251"]
cols: [
        "target_chembl_id",
        "smiles",
        "pchembl_value",
        "comment",
        "standard_type",
        "standard_relation",
        "document_year",
      ]
classification: false
px_placeholder: 3.99
px_thresh: 6.5
train_size: 0.2
val_size: 0.1

raw:
  path: data/raw/ligand_raw.tsv

processed:
  dir: data/processed/
  path: ${processed.dir}/ligand_proc.csv

final:
  path: data/final/ligand_train_data.pkl
