targets: ["CHEMBL226", "CHEMBL240", "CHEMBL251"]
cols: [
        "target_chembl_id",
        "smiles",
        "pchembl_value",
        "comment",
        "standard_type",
        "standard_relation",
        "document_year",
      ]
px_placeholder: 3.99
px_thresh: 6.5
test_size: 0.2

raw:
  dir: data/raw
  path: ${raw.dir}/ligand_raw.tsv

processed:
  dir: data/processed
  path: ${processed.dir}/ligand_proc.csv

final:
  dir: data/final
  path: ${final.dir}/ligand_train_data.pkl
