targets: ["CHEMBL226", "CHEMBL240", "CHEMBL251"]
cols: [
        "Target ChEMBL ID",
        "Smiles",
        "pChEMBL Value",
        "Comment",
        "Standard Type",
        "Standard Relation",
        "Document Year",
      ]
px_placeholder: 3.99
px_thresh: 6.5

raw:
  dir: data/raw

processed:
  dir: data/processed

final:
  dir: data/final
