name: rxitect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - tqdm
  - scikit-learn=0.22.1
  - numpy
  - pandas
  - jupyter
  - black
  - pytest
  - rdkit
  - matplotlib
  - selfies
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    - Sphinx==4.4.0
    - sphinxcontrib-napoleon==0.7
    - isort
    - gym
    - PyYAML
# Remember to download pytorch manually!