name: rx

channels:
  - pyg
  - pytorch
  - gpytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=1.11
  - botorch=0.7.2
  - cvxopt=1.3.0
  - torchmetrics=0.9.2
  - pyg=2.0.4
  - cudatoolkit=11.3
  - rdkit=2022.03.04
  - poetry>=1.1.4,<2.0
  - pip>=20.0
  - h5py=3.7.0
  - pip:
    - https://github.com/MolecularAI/aizynthfinder/archive/v3.4.0.tar.gz
