name: rxt

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=22.1.1
  - cudatoolkit=11.3
  - pytorch=1.11
  - dvc=2.10.0
  - hydra-core=1.1.1
  - notebook=6.4.10
  - seaborn=0.11.2
  - pandas=1.4.2
  - numpy=1.22.4
  - scikit-learn=1.1.1
  - rdkit=2022.3.2
  - selfies=2.1.0
  - wandb=0.12.16
  
  # dev dependencies below
  - pytest=6.2.5
  - pre-commit=2.17.0
  - jupyterlab=3.4.2
  - mypy=0.950
  - black=22.3.0
  - isort=5.10.1
  - flake8=4.0.1

  # pip-only dependencies below
  - pip:
    - pdoc3==0.10.0

