name: rxitect
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - tqdm
  - scikit-learn=0.22.1
  - numpy
  - pandas
  - jupyter
  - black
  - pytest
  - rdkit
  - matplotlib
  - selfies
  - dvc
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    - Sphinx==4.4.0
    - sphinxcontrib-napoleon==0.7
    - isort
    - gym
    - PyYAML
    - pytorch-ligthning