name: rxitect
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - tqdm
  - scikit-learn=0.22.1
  - numpy
  - pandas
  - jupyter
  - black
  - pytest
  - rdkit
  - matplotlib
  - pip:
    - git+https://github.com/reymond-group/RAscore.git@master
    - pyprojroot
    - Sphinx
    - isort
