_target_: rxitect.models.smiles_transformer.SmilesTransformer
max_lr: 0.001

net:
  _target_: rxitect.models.smiles_transformer.TransformerEncoder
  n_tokens: 45 # TODO: Make dynamic
  d_model: 256
  nhead: 8
  num_encoder_layers: 4
  dim_feedforward: 1024
  dropout: 0.1
  activation: relu
