params:
    targets: ["CHEMBL226", "CHEMBL240", "CHEMBL251"]
    cols: [
            "target_chembl_id",
            "smiles",
            "pchembl_value",
            "comment",
            "standard_type",
            "standard_relation",
            "document_year",
          ]
    classification: false
    px_placeholder: 3.99
    px_thresh: 6.5
    train_size: 0.2
    val_size: 0.1

raw: 
  path: ${hydra:runtime.cwd}/data/raw/ligand_raw.tsv

processed:
  dir: ${hydra:runtime.cwd}/data/processed
  name: ligand_proc.csv
  path: ${processed.dir}/${processed.name}

files:
  dir: ${hydra:runtime.cwd}/data/final
  train_data: ${files.dir}/ligand_train_data.csv
  test_data: ${files.dir}/ligand_test_data.csv
  val_data: ${files.dir}/ligand_val_data.csv