hyperparams:
  embed_size: 128
  hidden_size: 512
  is_lstm: true
  lr: 0.001

train_settings:
  epochs: 50
  dev: false
  n_workers: 2
  n_gpus: 1
  lr: 0.001

fine_tune_settings:
  epochs: 1000
  dev: false
  n_workers: 2
  n_gpus: 1
  lr: 0.0001
